name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel

    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: |
          pwd
          ls -al
          date +'%Y-%m-%d'
          cat /etc/os-release
          tar --version
          zstd --version
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: LICENSE
          tag: ${{ github.ref }}
          file_glob: false
          overwrite: true
          prerelease: false
          release_name: nightly-${{ steps.date.outputs.date }}
